name: Publish to GitHub Pages Repository

"on":
  push:
    branches:
      - main

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Creates output folder and remove .github
        run:  |
              mkdir output
              cp -r */*.md output
              cp -r */*.mp3 output
              # cp -r */*.html output
              rm -rf output/.github/*
      - name: Pushes to GitHub Pages repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@ssh-deploy-key
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: output/
          destination-github-username: 'CyberPunkRed'
          destination-repository-name: 'CyberPunkRed.github.io'
          user-name: 'MriesD'
          user-email: ${{ secrets.EMAIL }}
          commit-message: pushed from $GITHUB_REF
          target-branch: main
